-- departments table
CREATE TABLE IF NOT EXISTS departments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL
);

-- leaders table
CREATE TABLE IF NOT EXISTS leaders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  department_id BIGINT REFERENCES departments(id),
  phone TEXT,
  role TEXT,
  status TEXT DEFAULT 'Ativo'
);

-- events table
CREATE TABLE IF NOT EXISTS events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  date DATE NOT NULL,
  time TEXT,
  location TEXT,
  department_id BIGINT REFERENCES departments(id),
  status TEXT DEFAULT 'Pendente',
  type TEXT DEFAULT 'Interno',
  description TEXT
);

-- Enable RLS
ALTER TABLE departments ENABLE ROW LEVEL SECURITY;
ALTER TABLE leaders ENABLE ROW LEVEL SECURITY;
ALTER TABLE events ENABLE ROW LEVEL SECURITY;

-- Policies for public access (read)
CREATE POLICY "Public Read Departments" ON departments FOR SELECT USING (true);
CREATE POLICY "Public Read Leaders" ON leaders FOR SELECT USING (true);
CREATE POLICY "Public Read Events" ON events FOR SELECT USING (true);

-- Policies for authenticated users (admin)
CREATE POLICY "Admin All Departments" ON departments FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Admin All Leaders" ON leaders FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Admin All Events" ON events FOR ALL USING (auth.role() = 'authenticated');

-- Public can insert events (pre-agenda)
CREATE POLICY "Public Insert Events" ON events FOR INSERT WITH CHECK (true);

-- Default departments
INSERT INTO departments (name) VALUES 
('Campo'), ('Ensino/EBD'), ('Jovens'), ('Adolescentes'), ('Infantil'), ('Mulheres'),
('Família'), ('Missão'), ('Evangelismo'), ('Ação Social'), ('Discipulado'),
('Multimídia'), ('Louvor'), ('Eventos'), ('Obras')
ON CONFLICT (name) DO NOTHING;
